// export const GET_ERRORS = 'GET_ERRORS';
// export const USER_LOADING = 'USER_LOADING';


// authenticate

export const LOGIN_START = 'LOGIN_START';
// export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

//signup
export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';

//profile
export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE = 'PROFILE';
export const PROFILE_FAIL = 'PROFILE_FAIL';


//UPLOAD
export const UPLOAD_DP = 'UPLOAD_DP';
export const UPLOAD_DP_SUCCESS = 'UPLOAD_DP_SUCCESS';
export const UPLOAD_DP_FAIL = 'UPLOAD_DP_FAIL';


//contest
export const GET_CONTEST_REQUEST = 'GET_CONTEST_REQUEST';
export const GET_CONTEST_SUCCESS = 'GET_CONTEST_SUCCESS';
export const GET_CONTEST_FAIL = 'GET_CONTEST_FAIL';

//contestant
export const ADD_CONTESTANT_REQUEST = 'ADD_CONTESTANT_REQUEST';
export const ADD_CONTESTANT_SUCCESS = 'ADD_CONTESTANT_SUCCESS';
export const ADD_CONTESTANT_FAIL = 'ADD_CONTESTANT_FAIL';

//update paypal email
export const UPDATE_PAYPAL_EMAIL_REQUEST = 'UPDATE_PAYPAL_EMAIL_REQUEST';
export const UPDATE_PAYPAL_EMAIL_SUCCESS = 'UPDATE_PAYPAL_EMAIL_SUCCESS';
export const UPDATE_PAYPAL_EMAIL_FAIL = 'UPDATE_PAYPAL_EMAIL_FAIL';

//update password for logged in user
export const UPDATE_PASSWORD_REQUEST = 'UPDATE_PASSWORD_REQUEST';
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS';
export const UPDATE_PASSWORD_FAIL = 'UPDATE_PASSWORD_FAIL';

//get all contestants
export const GET_ALL_CONTESTANTS_REQUEST = 'GET_ALL_CONTESTANTS_REQUEST';
export const GET_ALL_CONTESTANTS_SUCCESS = 'GET_ALL_CONTESTANTS_SUCCESS';
export const GET_ALL_CONTESTANTS_FAIL = 'GET_ALL_CONTESTANTS_FAIL';

//user search action
export const SEARCH_CONTESTANTS_REQUEST = 'SEARCH_CONTESTANTS_REQUEST';
export const SEARCH_CONTESTANTS_SUCCESS = 'SEARCH_CONTESTANTS_SUCCESS';
export const SEARCH_CONTESTANTS_FAIL = 'SEARCH_CONTESTANTS_FAIL';
